### PR TITLE
Basically support CombinedDiff for merge commit.

### PR DESCRIPTION
**Pull request by EbenZhang**

### CODE REVIEW

**Comment by Radrik5** [comment]
Thanks a lot for this work! I'm going to try it today.

**Comment by Radrik5** [comment]
Couple of suggestions:
1. Please use `git diff-tree` commands instead of `git show`:
   - `git diff-tree --name-status --cc --no-commit-id {commit} --`
   - `git diff-tree --cc --no-commit-id {commit} -- {filename}`
2. Please consider using combined (-c) diff by default instead of compressed combined (--cc) diff. There is a good explanation of the difference at http://git.661346.n2.nabble.com/log-p-hides-changes-in-merge-commit-td5896280.html

**Comment by Radrik5** [comment]
Also, there is an issue with highlighting diff to the second parent:
image

**Comment by EbenZhang** [comment]
@Radrik5, thanks for reviewing, I've done the changes to 
- use `diff-tree` instead of `git show`
- add an option to use `patience` diff algorithm
- add a workaround for the highlight issue

**Pull request merged**
